# Generated by Django 5.2.4 on 2025-08-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=4000, null=True)),
                ('bwrite', models.DateField(blank=True, null=True)),
                ('readcnt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buser',
            fields=[
                ('buserno', models.IntegerField(primary_key=True, serialize=False)),
                ('busername', models.CharField(max_length=10)),
                ('buserloc', models.CharField(blank=True, max_length=10, null=True)),
                ('busertel', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'buser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gogek',
            fields=[
                ('gogekno', models.IntegerField(primary_key=True, serialize=False)),
                ('gogekname', models.CharField(max_length=10)),
                ('gogektel', models.CharField(blank=True, max_length=20, null=True)),
                ('gogekjumin', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'db_table': 'gogek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jikwon',
            fields=[
                ('jikwonno', models.IntegerField(primary_key=True, serialize=False)),
                ('jikwonname', models.CharField(max_length=10)),
                ('jikwonjik', models.CharField(blank=True, max_length=10, null=True)),
                ('jikwonpay', models.IntegerField(blank=True, null=True)),
                ('jikwonibsail', models.DateField(blank=True, null=True)),
                ('jikwongen', models.CharField(blank=True, max_length=4, null=True)),
                ('jikwonrating', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'jikwon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sangdata',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('sang', models.CharField(blank=True, max_length=20, null=True)),
                ('su', models.IntegerField(blank=True, null=True)),
                ('dan', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sangdata',
                'managed': False,
            },
        ),
    ]
